<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Recent logins_fb_logo _8ilh img</name>
   <tag></tag>
   <elementGuidId>3b8262d8-7881-49fa-9a03-a11c33d8c57f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.fb_logo._8ilh.img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Facebook&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>337afd28-374e-4b67-a9d7-973734d5daa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fb_logo _8ilh img</value>
      <webElementGuid>9df11af9-f511-48cc-9ec9-ab8b0856d518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.xx.fbcdn.net/rsrc.php/y1/r/4lCu2zih0ca.svg</value>
      <webElementGuid>a36a9406-d76d-468e-b8b1-d57c7bc49098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Facebook</value>
      <webElementGuid>82124f1b-5d7f-4e7f-9e9d-b6f0a23a06dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[1]/div[@class=&quot;_95k9 _8esf _8f3m _8ilg _8icx _95kc _95kb&quot;]/div[@class=&quot;_5aj7 _m--&quot;]/div[@class=&quot;_4bl9 _ihf&quot;]/div[@class=&quot;_8ice&quot;]/img[@class=&quot;fb_logo _8ilh img&quot;]</value>
      <webElementGuid>20798acb-b73d-4665-b4b3-7c55aa7ea482</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/div/img</value>
      <webElementGuid>7b595d91-7a19-4375-90f8-040556b6069a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Facebook']</value>
      <webElementGuid>74fa541c-a331-4faf-92d1-754af7bef141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e4e0e334-d85d-4d2d-9301-326b77052e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.xx.fbcdn.net/rsrc.php/y1/r/4lCu2zih0ca.svg' and @alt = 'Facebook']</value>
      <webElementGuid>c5f2fa2e-4039-45d6-af15-594c63dc80cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
