<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The password youve entered is incorrect</name>
   <tag></tag>
   <elementGuidId>e980ba11-bc00-4169-b385-e521b941cdd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='u_0_1_H6']/div/div[2]/div/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span._akzt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;The password you've entered is incorrect.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>82a16e30-5b5c-42e1-b5f7-8186ae24e8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_akzt</value>
      <webElementGuid>ab8d6e87-d710-4655-8b0d-61e3fcce4abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The password you've entered is incorrect.</value>
      <webElementGuid>ef9158a8-0fe0-4b1a-8091-e1106e31acec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_1_H6&quot;)/div[@class=&quot;mtl mbm ptm uiInterstitial _aklr uiInterstitialLarge uiBoxWhite&quot;]/div[@class=&quot;phl ptm uiInterstitialContent&quot;]/div[1]/div[@class=&quot;pam uiBoxGray&quot;]/div[1]/span[@class=&quot;_akzt&quot;]</value>
      <webElementGuid>22751980-e09f-4e7c-9b3c-a993bafb5c60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_1_H6']/div/div[2]/div/div/div/span[2]</value>
      <webElementGuid>ef4421e4-8ea5-4977-aafc-f02a40048f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There was a problem while logging you in, but we can send a login code to:'])[1]/preceding::span[1]</value>
      <webElementGuid>74a36ad8-08a1-4bca-a84a-1720a1d13d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bangsalman@yahoo.co.id'])[1]/preceding::span[1]</value>
      <webElementGuid>3ba97ade-a828-4635-8cc6-b396ad8c8e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>29d21179-2aca-4bd4-bac2-4cb7b7fb6606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = concat(&quot;The password you&quot; , &quot;'&quot; , &quot;ve entered is incorrect.&quot;) or . = concat(&quot;The password you&quot; , &quot;'&quot; , &quot;ve entered is incorrect.&quot;))]</value>
      <webElementGuid>6f479842-bb6e-4e3b-ace3-875ffb15bc61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
